baseURL: https://dapr.io/
languageCode: en-us
title: Dapr - portable, event-driven, serverless runtime.
theme: clean-landing

disableKinds:
 -taxonomy
 -taxonomyTerm

params:
  description: Dapr is a portable, event-driven, runtime for building distributed applications across cloud and edge.
  openGraph: true
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/temp-logo.svg
   link: https://dapr.io/
  font:
    name: "Work Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: dapr
    # Hero subtitle (optional)
    subtitle: An event-driven, portable runtime for building microservices on cloud and edge.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /#
  - title: About
    url: /#about
  - title: Download
    url: /#download
  - title: Docs
    url: https://docs.dapr.io
  - title: Blog
    url: https://blog.dapr.io/posts
  - title: Community
    url: /#community
  about:
    title: about
    tiles:
    - title: Powerful Building Blocks
      icon: blocks
      text: Dapr enables easy, event-driven, stateful, microservices development.
    - title: No Limits
      icon: code
      text: Dapr works with any programming language - on any cloud or edge.
    - title: Open API
      icon: openapi
      text: Dapr provides consistency and portability, via standard open APIs
    - title: Open Source
      icon: community
      text: Dapr is an open source and vendor neutral project.
  footer:
    logo: dapr.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://twitter.com/DaprDev
      icon: twitter
      name: Twitter
    - link: https://gitter.im/Dapr
      icon: users
      name: Gitter
    - link: https://github.com/dapr/dapr
      icon: github
      name: Github