######################## default configuration ####################
baseURL = "https://dapr.io/"
title = "Dapr - Distributed Application Runtime"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

# Reo
[params.reo]
clientID = "966c1ae3541ca2f"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Docs"
URL = "https://docs.dapr.io/"
weight = 1

[[menu.main]]
name = "Learn"
URL = "/learn/"
weight = 2

[[menu.main]]
name = "Community"
URL = "/community/"
weight = 3

[[menu.main]]
name = "Enterprise"
weight = 5

[[menu.main]]
name = "News & Media"
identifier = "News & Media"
weight = 4

[[menu.main]]
name = "Blog"
URL = "https://blog.dapr.io/posts"
parent = "News & Media"
weight = 1

[[menu.main]]
name = "Case studies"
URL = "/testimonials/"
parent = "News & Media"
weight = 1

[[menu.main]]
name = "Logos"
URL = "https://github.com/cncf/artwork/blob/master/examples/graduated.md#dapr-logos"
parent = "News & Media"
weight = 3

[[menu.main]]
name = "Enterprise"
URL = "/enterprise/"
weight = 5

[[menu.main]]
name = "中国社区"
URL = "https://cn.dapr.io"
weight = 6

# footer menu
[[menu.footer_column1]]
name = "Concepts"
URL = "https://docs.dapr.io/concepts/"
weight = 1

[[menu.footer_column1]]
name = "Getting Started"
URL = "https://docs.dapr.io/getting-started/"
weight = 2

[[menu.footer_column1]]
name = "Quickstarts"
URL = "https://docs.dapr.io/getting-started/quickstarts/"
weight = 3

[[menu.footer_column1]]
name = "Dapr University"
URL = "https://www.diagrid.io/dapr-university"
weight = 4

[[menu.footer_column2]]
name = "GitHub"
URL = "https://github.com/dapr/community"
weight = 1

[[menu.footer_column2]]
name = "Discord"
URL = "https://bit.ly/dapr-discord"
weight = 2

[[menu.footer_column2]]
name = "YouTube"
URL = "https://www.youtube.com/@daprdev"
weight = 3

[[menu.footer_column2]]
name = "LinkedIn"
URL = "https://www.linkedin.com/company/daprdev/"
weight = 4

[[menu.footer_column3]]
name = "Blog"
URL = "https://blog.dapr.io/posts"
weight = 1

[[menu.footer_column3]]
name = "Case studies"
URL = "/testimonials/"
weight = 2

[[menu.footer_column3]]
name = "Logos"
URL = "https://github.com/cncf/artwork/blob/master/examples/graduated.md#dapr-logos"
weight = 3

[[menu.footer_column4]]
name = "Terms"
URL = "https://www.linuxfoundation.org/legal/terms"
weight = 1

[[menu.footer_column4]]
name = "Privacy"
URL = "https://www.linuxfoundation.org/legal/privacy-policy"
weight = 2

[[menu.footer_column4]]
name = "Trademarks"
URL = "https://www.linuxfoundation.org/legal/trademark-usage"
weight = 3

# menu media

[[menu.media]]
name = "twitter"
URL = "https://twitter.com/daprdev"
weight = 1

[[menu.media]]
name = "github"
URL = "https://github.com/dapr"
weight = 2

[[menu.media]]
name = "youtube"
URL = "https://www.youtube.com/@daprdev"
weight = 3

#################### default parameters ################################
[params]
logo = "images/dapr.svg"
logo_width = "60px"
# Meta data
description = "APIs for building secure and reliable microservices"
keywords = "dapr, microservices, distributed applications, runtime, kubernetes"
author = "Dapr Maintainers"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
footer_menu_column1 = "Learn"
footer_menu_column2 = "Community"
footer_menu_column3 = "News & Media"
footer_menu_column4 = "Legal"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = false
label = "Get started"
link = "https://docs.dapr.io/getting-started/"
